import type {
  DailyOverviewClaudePayloadV02,
  SignalEventClaudePayloadV02,
} from "./types.ts";

function prettyJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

export function buildSignalEventPromptV02(
  payload: SignalEventClaudePayloadV02,
): string {
  return [
    "You are validating one ByteSiren v0.2 Signal Event.",
    "",
    "Task:",
    "- Treat the item as a compact evidence-window event.",
    "- Use the exact UTC time and date in the payload.",
    "- Convert to ET where macro events may matter.",
    "- Search for time-aligned public context tied to this evidence window.",
    "- Use chart context only as descriptive evidence, not as proof of a news cause.",
    "- Do not infer a news cause from chart pattern alone.",
    "- Attempt event-specific source matching first.",
    "- If no time-aligned source supports a cause, return Market Backdrop or No Clear Cause.",
    "- Do not force a cause.",
    "- Do not provide trading advice.",
    "- Return JSON only.",
    "",
    "Allowed classifications:",
    "- Focused Cause",
    "- Likely Cause",
    "- Market Backdrop",
    "- No Clear Cause",
    "- Claude Limited",
    "",
    "Source tags:",
    "- Focused catalyst source",
    "- Likely cause source",
    "- Backdrop source",
    "- Price check source",
    "",
    "Source rules:",
    "- Focused Cause requires at least one Focused catalyst source.",
    "- Likely Cause requires at least one Focused catalyst source or Likely cause source.",
    "- If only Backdrop sources remain, classification should be Market Backdrop.",
    "- If only Price check sources remain, classification should be No Clear Cause or Market Backdrop depending on context.",
    "- Generic price recaps cannot become causes.",
    "",
    "Required output shape:",
    prettyJson({
      mode: "signal_event",
      item_id: payload.target_id,
      classification:
        "Focused Cause | Likely Cause | Market Backdrop | No Clear Cause | Claude Limited",
      confidence: "high | medium | low",
      headline: "short public headline",
      collapsed_summary: "short public summary",
      context_details: "source-grounded context",
      why_this_classification: "short explanation",
      source_support: "high | medium | low | none",
      source_timing_alignment: "exact | same_day | broad | poor | none",
      sources: [
        {
          title: "article title",
          publisher: "publisher",
          url: "exact article URL",
          published_at: "ISO timestamp or null",
          tag: "Focused catalyst source | Likely cause source | Backdrop source | Price check source",
          why_relevant: "short reason",
        },
      ],
      rejected_or_ignored_source_notes: ["safe short note"],
      validation_flags: {},
      detector_feedback: {},
    }),
    "",
    "Signal Event payload:",
    prettyJson(payload),
  ].join("\n");
}

export function buildDailyOverviewPromptV02(
  payload: DailyOverviewClaudePayloadV02,
): string {
  return [
    "You are validating one ByteSiren v0.2 Daily Overview.",
    "",
    "Task:",
    "- Treat the item as full UTC-day context.",
    "- Use the Daily Overview fields, Signal Events for that day, and deterministic Market Stories for that day if included.",
    "- Search for relevant public sources for the UTC day.",
    "- Do not force a single cause for the whole day.",
    "- Do not infer day-level cause from chart context alone.",
    "- Do not use Signal Event cause labels as the Daily Overview main label.",
    "- Do not provide trading advice.",
    "- Return JSON only.",
    "",
    "Allowed Daily Overview labels:",
    "- Daily Context",
    "- Quiet Day",
    "- Mixed Day",
    "- Volatile Day",
    "- Risk-on Day",
    "- Risk-off Day",
    "- No Major Driver",
    "- Claude Limited",
    "",
    "Daily Overview source tags:",
    "- Main daily context source",
    "- Supporting daily source",
    "- Backdrop source",
    "- Price check source",
    "",
    "Required output shape:",
    prettyJson({
      mode: "daily_overview",
      item_id: payload.target_id,
      date_utc: payload.date_utc,
      daily_label:
        "Daily Context | Quiet Day | Mixed Day | Volatile Day | Risk-on Day | Risk-off Day | No Major Driver | Claude Limited",
      confidence: "high | medium | low",
      headline: "short day headline",
      collapsed_summary: "short day summary",
      context_details: "source-grounded daily context",
      market_tone_summary: "short tone summary",
      notable_drivers: [
        {
          driver: "driver name or context",
          source_support: "high | medium | low",
          why_relevant: "short reason",
        },
      ],
      sources: [
        {
          title: "article title",
          publisher: "publisher",
          url: "exact article URL",
          published_at: "ISO timestamp or null",
          tag: "Main daily context source | Supporting daily source | Backdrop source | Price check source",
          why_relevant: "short reason",
        },
      ],
      validation_flags: {},
      detector_feedback: {},
    }),
    "",
    "Daily Overview payload:",
    prettyJson(payload),
  ].join("\n");
}
